### ISSUE TITLE
Steps to releasing gRPC 2.0

### ISSUE THREAD

**Issue by murgatroid99** [grpc/grpc-node#15]
- [x] Move the low-level pure JavaScript (TypeScript) code into `packages/grpc-js-core` (#14)
- [x] Import the existing grpc package into `packages/grpc-native-core` (#17)
  - [x] Create a submodule in `packages/grpc-native-core` that points to the `grpc/grpc` repository for the C core dependency (#18)
  - [ ] Divide that code into several packages
    - [ ] Move all protobuf.js related code into `packages/grpc-protobufjs`
    - [ ] Move other code that is shared between implementations (currently just `grpc.makeGenericClientConstructor`) into `packages/grpc-surface`
    - [x] Move `grpc-tools` code into `packages/grpc-tools` (#20)
    - [x] Move health checking code into `packages/grpc-health-check` (#20)
    - [x] Move API surface-level unit tests, interop tests, performance tests, etc. into `tests` in the repository root, and create a pseudo package to handle their dependencies on the other packages in the repository
- [ ] Create the gRPC metapackage in `packages/grpc` that initially depends on `grpc-native`.
- [ ] Add feature/capability enabling functionality
- [ ] Upgrade the dependency on Protobuf.js to version 6.
- [ ] Make any other breaking changes (TODO(murgatroid99): insert a reference to a relevant gRFC)

**Comment by nicolasnoble** [comment]
This one isn't really relevant anymore. Closing with prejudice.
